title: Personal Blog & Site About Things I Code
description: description
author: Chris Hsieh
github-site: https://github.com/JumpingRock/JumpingRock.io
github: https://github.com/JumpingRock/
about: Hi I am a Software Dev I like Java. My alternative alias is JumpingRock.
disqus_shortname: JumpingCode
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "https://twitter.com/place here"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/JumpingRock"

share:
  twitter_username: twittername
  fb_appid: 32423432432

urls:
    - text: About Me 
      url: /about/
    - text: Projects (Nothing yet... Stay Tuned!)
      url: /projects/
    - text: XML Feed 
      url: /feed.xml
    - text: My Github 
      url: https://github.com/JumpingRock

url: "http://christopherhsieh.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist