title: Personal Blog of My Coding Adventures!
description: My Personal Coding Problems
author: Chris Hsieh
github-site: https://github.com/JumpingRock/JumpingRock.io
github: https://github.com/JumpingRock/
about: Hi I am a Software Dev I like Java
disqus_shortname: JumpingCode
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/place here"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: twittername
  fb_appid: 32423432432

urls:
    - text: About Me --Under Construction--
      url: /about/
    - text: Projects --Under Construction--
      url: /projects/
    - text: Github --Just Links you to my GitHub, will replace with an icon--
      url: https://github.com/JumpingRock
    - text: XML Feed --Under Construction--
      url: /feed.xml

url: "http://christopherhsieh.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist