title: title
description: description
author: Christopher Hsieh
github-site: https://github.com/Christopher-Hsieh/Christopher-Hsieh.io
github: https://github.com/Christopher-Hsieh
about: about
disqus_shortname: disqus-shortme
google_analytics: UA-83903069-1

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    # - icon: fa-facebook
    #   link: "#"
    # - icon: fa-twitter
    #   link: "https://twitter.com/place here"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/JumpingRock"

share:
  twitter_username: twittername
  fb_appid: 32423432432

urls:
    - text: About Me 
      url: /about/
    - text: Projects (Nothing yet... Stay Tuned!)
      url: /projects/
    - text: XML Feed 
      url: /feed.xml
    - text: My Github 
      url: https://github.com/JumpingRock

url: "http://christopherhsieh.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

theme: jekyll-theme-leap-day