export const profile = {
  name: 'Christopher J. Hsieh',
  handle: '@christopher-hsieh',
  title: 'Lead Software Engineer',
  status:
    'Open to senior / staff / lead opportunities (seeking teams obsessed with both the craft & the people using it)',
  location: 'Fishers, IN',
  email: 'christopher.j.hsieh@gmail.com',
  phone: '(574) 514-4447',
  linkedin: 'https://www.linkedin.com/in/christopher-j-hsieh',
  github: 'https://github.com/Christopher-Hsieh',
  pitch:
    'Engineering leader with 10+ years shipping web applications across teams, orgs, & disciplines. Greenfield to production at Nike, Liberty Mutual — micro frontends, platforms, and the people who ship them.',
  summary: [
    'I build and scale web applications across teams and orgs — most recently at Nike where I own platform-wide initiatives and high-traffic surfaces like Nike.com/retail.',
    'An MBA-trained engineer focused on the cross-functional leadership it takes to actually ship — partnering with design, product, and a dozen+ teams to evangelize standards and move work from greenfield to production.',
  ],
  stats: [
    { value: '10+', label: 'Years building for the web' },
    { value: '1M+', label: 'Peak sessions / day on Nike.com/retail' },
    { value: '$100K+', label: 'Premiums / day generated by LM platform I led' },
    { value: '400+', label: 'Engineers upskilled through programs I built' },
  ],
};
